#!/usr/bin/env node

const commander = require("commander");

commander
  .version("0.0.1-alpha1")
  .command("list", "List all kubeconfigs")
  .alias("l")
  .command("activate [kubeconfig.{yml,yaml}]", "Activate a kubeconfig")
  .alias("a")
  .command("get [kubeconfig.{yml,yaml}]", "Get a kubeconfig")
  .alias("g")
  .command("current", "Get the current kubeconfig")
  .alias("c")
  .parse(process.argv);
